# Generated by Django 4.1.3 on 2022-12-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_profile_address_remove_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='Profile Owner'),
        ),
    ]
