# Generated by Django 4.1.3 on 2023-01-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='carriers',
            field=models.CharField(default='att', max_length=15),
        ),
    ]
