# Generated by Django 4.1.3 on 2023-01-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profile_carriers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='carriers',
        ),
    ]
