# Generated by Django 4.1.3 on 2023-01-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_profile_carriers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='carrier',
            field=models.CharField(default='att', max_length=15),
        ),
    ]
